# Use root/example as user/password credentials
version: '3.1'

services:

  server:
    build: .
    command: bash -c "npm run build && npm run dev"
    restart: always
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules
    ports:
      - "8001:8001"
    depends_on:
      - mongo
    environment:
      DATABASE_URL: mongodb://root:example@mongo:27017

  mongo:
    image: mongo
    restart: always
    
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: hakuchat

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017
    
